#!/bin/bash

# nickmahda@gmail.com

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

DIR=$(pwd)

git submodule update --init --recursive --remote

while getopts "pcb" o; do
    case "$o" in
        p) p=1;;
        c) c=1;;
        b) b=1;;
    esac
done

bacup() {
    if [ -e ~/."$1" ]; then
        mkdir -pv $DIR/backup
        mv -v ~/."$1" $DIR/backup/"$1"
    fi
}

mov () {
    f=$(sed "s/^\.//" <<< "$1")
    bacup $f
    cmp --silent ~/."$f" "$f" || ln -sfv "$DIR/$f" ~/."$f"
}

for file in vars zshrc gitconfig tmux.conf.local p10k.zsh; do mov $file; done
for dir in zsh vim; do mov $dir; done

bacup vimrc
ln -sfv $DIR/vim/.vimrc ~/.vimrc

[ "$b" ] && bacup bashrc
echo "[ -f ~/.vars ] && source ~/.vars" >> ~/.bashrc

cd tmux && mov .tmux.conf
cd .. || exit

if [[ "$OSTYPE" == "darwin"* ]]; then
    [ "$b" ] && bacup bash_profile
    echo "[ -f ~/.bashrc ] && source ~/.bashrc" >> ~/.bash_profile

    if [ -z "$(which brew)" ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    if [ "$p" ]; then
        /opt/homebrew/bin/brew install coreutils gcc nano pkg-config python tmux vim youtube-dl zsh
        # cmake emacs gnu-chess htop nginx opencv tree
        /usr/local/bin/pip3 install -r "$DIR"/requirements.txt
    fi

    if [ "$c" ]; then
        /opt/homebrew/bin/brew cask install apple-juice discord dozer eqmac flux google-backup-and-sync google-chrome iterm2 karabiner-elements overkill selfcontrol slack spotify the-unarchiver telegram visual-studio-code
        # appcleaner docker eqmac firefox gimp latest omnidisksweeper ticktick vnc-viewer zotero
    fi

    cp "$DIR"/BlexMono.ttf ~/Library/Fonts/

elif [[ "$OSTYPE" == "linux"* ]]; then
    if [ "$p" ]; then
        sudo apt install git pkg-config python3-pip tmux vim zsh # emacs htop gnuchess
        usr/bin/pip3 install -r "$DIR"/requirements.txt
    fi
fi

# sudo ln -sfv "$DIR"/zsh/powerlevel10k/powerlevel10k.zsh-theme /usr/local/share/zsh/site-functions/prompt_powerlevel10k_setup

touch ~/.path
touch ~/.vars.local

echo "Done"

cd "$DIR" || exit
