#!/bin/bash

# Nicholas Mahdavi
# nickmahda@gmail.com

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

DIR=$(pwd)

git submodule init && git submodule update

while getopts "pcb" o; do
    case "$o" in
        p) p=1;;
        c) c=1;;
        b) b=1;;
    esac
done

mov () {
  [ -e ~/."$1" ] && { mkdir -pv backup; mv -v ~/."$1" backup/"$1"; }
  ln -sfv "$DIR/$1" ~/."$1"
}

for f in var zshrc gitconfig tmux.conf.local p10k.zsh; do
  cmp --silent ~/."$f" "$f" && continue
  mov $f
done

(cd tmux || exit

cmp --silent ~/.tmux.conf .tmux.conf
mov .tmux.conf)

[ "$b" ] && [ -e ~/.bashrc ] && { mkdir -pv backup; mv -v ~/.bashrc backup/bashrc; }
echo -e "[ -f ~/.var ] && source ~/.var" >> ~/.bashrc

[ -d ~/.zsh ] && mv -v ~/.zsh backup/zsh
ln -sfv "$DIR/zsh" ~/.zsh

if [[ "$OSTYPE" == "darwin"* ]]; then
    [ -e ~/.bash_profile ] && { mkdir -pv backup; mv -v ~/.bash_profile backup/bash_profile; }
    echo -e "[ -f ~/.bashrc ] && source ~/.bashrc" > ~/.bash_profile

    if [ -z "$(which brew)" ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    sudo chown -R "$(whoami)" "$(brew --prefix)"/*

    [ "$p" ] && brew install coreutils gcc nano pkg-config python tmux vim youtube-dl zsh # cmake emacs gnu-chess htop nginx opencv tree

    [ "$c" ] && brew cask install appcleaner apple-juice discord dozer eqmac firefox flux gimp google-backup-and-sync google-chrome iterm2 karabiner-elements latest omnidisksweeper overkill selfcontrol slack spotify the-unarchiver telegram ticktick visual-studio-code vnc-viewer zotero # docker

    cp "$DIR"/BlexMono.ttf ~/Library/Fonts/

    # curl https://bootstrap.pypa.io/ez_setup.py | python

    [ "$c" ] && /usr/local/bin/pip3 install -r ./requirements.txt

elif [[ "$OSTYPE" == "linux"* ]]; then
    [ "$p" ] && sudo apt install pkg-config python3-dev tmux zsh # emacs htop gnuchess

    cp "$DIR"/BlexMono.ttf ~/.fonts/
    fc-cache -fv

    [ "$c" ] && /usr/bin/pip3 install "$DIR"/requirements.txt

    mv ~/.var ~/.variables
fi

sudo ln -sfv "$DIR"/zsh/powerlevel10k/powerlevel10k.zsh-theme /usr/local/share/zsh/site-functions/prompt_powerlevel10k_setup

touch ~/.path

echo "Moving to vim install"

cd "$DIR" || exit
./viminstall
