#!/bin/bash
# Nicholas Mahdavi
# nickmahda@gmail.com

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

DIR=`pwd`

[ -d ~/.vim/ ] && mv ~/.vim/ ~/.vim.backup/
[ -f ~/.vimrc ] && mv ~/.vimrc ~/.vimrc.backup

git clone https://github.com/nickmahd/.vim.git ~/.vim

cd ~/.vim

git submodule init && git submodule foreach --recursive git pull origin master

ln -sfv ~/.vim/vimrc ~/.vimrc

echo "Vim is fully set up"
